import math
import random
import time
import numpy as np
import matplotlib.pyplot as plt
from granger_test import granger
from data_generation import generate_continue_data, GMM,forward_shift_continue_data
from Util import zero_change, change_to_zero_one, get_type_array_with_quantile, get_type_array_with_quantile_change,bh_procedure,get_type_array_with_quantile_change2
from Disc import calculate_difference, calculate_difference_with_weight_window, calculate_difference_with_quantile2,calculate_difference_with_weight,calculate_difference_with_quantile,calculate_difference_step,fast_calculate_difference
from cute import bernoulli, bernoulli2, cbernoulli, cbernoulli2
from Util import bh_procedure2, Pro






"""
window_length: the size of window
array_length: the length of tested array
is_causal: is causality test
is_linear: in causality test, if the cause and effect data is linear related
is_GMM: is data generated by GMM
is_test_CUTE: is test CUTE encoding consistency
noise: the standard deviation of noise:0.1, 0.2, 0.3
"""
def test_data(window_length, array_length, is_causal, is_linear, is_GMM, is_test_CUTE, noise):
    counter11 = 0
    counter10 = 0
    counter01 = 0
    counter00 = 0
    counter11_01 = 0
    counter10_01 = 0
    counter01_01 = 0
    counter00_01 = 0
    counter_undecided = 0
    counter_true = 0
    counter_false = 0
    p_array_CUTE1 = []
    p_array_CUTE2 = []
    p_array_improve_CUTE1 = []
    p_array_improve_CUTE2 = []
    p_array1 = []
    p_array2 = []

    pros1 = []
    pros2 = []

    pros_cute = []

    pros_cute_counter = 0
    for i in range(0, 1000):
        if is_causal:
            lag = random.randint(1, 3)
            cause, effect = generate_continue_data(array_length, lag, noise)
            cause_tmp = list(cause)
            effect_tmp = list(effect)
            cause = zero_change(cause)
            effect = zero_change(effect)
            #cause = zero_change(cause)
            #effect = zero_change(effect)
            if not is_linear:
                for i in range(0, len(effect)):
                    effect[i] = math.exp(effect[i])
        else:
            lag = 5  # give a fixed lag if no causality
            if is_GMM:
                cause = GMM(3, array_length)
                effect = GMM(5, array_length)
            else:
                cause = np.random.standard_normal(array_length)
                effect = np.random.standard_normal(array_length)
            cause_tmp = list(cause)
            effect_tmp = list(effect)
            cause = zero_change(cause)
            effect = zero_change(effect)

        flag1 = False
        ce_p = granger(cause, effect, lag)
        ce_p_reverse = granger(effect[::-1], cause[::-1], lag)
        if ce_p < 0.05 and ce_p_reverse<0.05:
            flag1 = True
        flag2 = False
        ce2_p = granger(effect, cause, lag)
        ce2_p_reverse = granger(cause[::-1],effect[::-1],lag)
        if ce2_p < 0.05 and ce2_p_reverse<0.05:
            flag2 = True
        if flag1 and flag2:
            counter11 += 1
        elif flag1 and not flag2:
            counter10 += 1
        elif not flag1 and flag2:
            counter01 += 1
        elif not flag1 and not flag2:
            counter00 += 1
        if is_test_CUTE:
            cause2 = change_to_zero_one(cause)
            effect2 = change_to_zero_one(effect)
        else:
            cause2 = get_type_array_with_quantile(cause)
            effect2 = get_type_array_with_quantile(effect)
        flag3 = False
        ce3_p = granger(cause2, effect2, lag)
        ce3_p_reverse = granger(effect2[::-1], cause2[::-1], lag)
        if ce3_p < 0.05 and ce3_p_reverse<0.05:
            flag3 = True
        flag4 = False
        ce4_p = granger(effect2, cause2, lag)
        ce4_p_reverse = granger(cause2[::-1],effect2[::-1],lag)
        if ce4_p < 0.05 and ce4_p_reverse<0.05:
            flag4 = True
        if flag3 and flag4:
            counter11_01 += 1
        elif flag3 and not flag4:
            counter10_01 += 1
        elif not flag3 and flag4:
            counter01_01 += 1
        elif not flag3 and not flag4:
            counter00_01 += 1
        cause_tra = cause[::-1]
        effect_tra = effect[::-1]
        delta_ce = calculate_difference(cause, effect, window_length)
        delta_ec = calculate_difference(effect, cause, window_length)

        delta_ce2 = calculate_difference(effect_tra, cause_tra, window_length)
        delta_ec2 = calculate_difference(cause_tra, effect_tra, window_length)
        # print 'cause' + ' -> ' + 'effect' + ':' + str(delta_ce)
        # print 'effect' + ' -> ' + 'cause' + ':' + str(delta_ec)
        if delta_ce > delta_ec and delta_ce - delta_ec >= -math.log(0.05, 2):
            counter_true += 1
        elif delta_ec > delta_ce and delta_ec - delta_ce >= -math.log(0.05, 2):
            counter_false += 1
        else:
            counter_undecided += 1
        p = math.pow(2, -abs(delta_ce - delta_ec))
        p_tra = math.pow(2, -abs(delta_ce2 - delta_ec2))
        p_array1.append(p)
        element = Pro()
        element.p1 = p
        element.p2 = p_tra
        if delta_ce-delta_ec>0:
            element.direction1 = 0
        else:
            element.direction1 = 1
        if delta_ce2-delta_ec2>0:
            element.direction2 = 0
        else:
            element.direction2 = 1
        pros1.append(element)

        p = math.pow(2, -(delta_ec - delta_ce))
        p_tra = math.pow(2, -(delta_ec2 - delta_ce2))
        p_array1.append(p)
        element = Pro()
        element.p1 = p
        element.p2 = p_tra
        pros2.append(element)

        p_array2.append(math.pow(2, -(delta_ec - delta_ce)))
        cause = change_to_zero_one(cause_tmp)
        effect = change_to_zero_one(effect_tmp)
        cause2effect = bernoulli2(effect, window_length) - cbernoulli2(effect, cause, window_length)
        effect2cause = bernoulli2(cause, window_length) - cbernoulli2(cause, effect, window_length)
        cause2effect_reverse = bernoulli2(cause[::-1], window_length) - cbernoulli2(cause[::-1], effect[::-1], window_length)
        effect2cause_reverse = bernoulli2(effect[::-1], window_length) - cbernoulli2(effect[::-1], cause[::-1], window_length)
        p = math.pow(2, -abs(cause2effect - effect2cause))
        p_tra = math.pow(2, -abs(cause2effect_reverse - effect2cause_reverse))
        element = Pro()
        element.p1 = p
        element.p2 = p_tra
        if cause2effect - effect2cause > 0:
            element.direction1 = 0
        else:
            element.direction1 = 1
        if cause2effect_reverse - effect2cause_reverse > 0:
            element.direction2 = 0
        else:
            element.direction2 = 1
        #if element.direction1==element.direction2:
        #    if p<=0.05 and p_tra<=0.05:
        #        pros_cute_counter+=1
        pros_cute.append(element)
        p = math.pow(2, -(cause2effect - effect2cause))
        p_array_improve_CUTE1.append(p)
        p_array_improve_CUTE2.append(math.pow(2, -(effect2cause - cause2effect)))
        cause2effect = bernoulli(effect) - cbernoulli(effect, cause)
        effect2cause = bernoulli(cause) - cbernoulli(cause, effect)
        p_array_CUTE1.append(math.pow(2, -(cause2effect - effect2cause)))
        p_array_CUTE2.append(math.pow(2, -(effect2cause - cause2effect)))
    """
    print "Continuous data, Granger causality test:"
    print "Two-way causality:" + str(counter11)
    print "Correct causality:" + str(counter10)
    print "Wrong causality:" + str(counter01)
    print "No causality:" + str(counter00)
    print "-----------------"
    print "Encoding data, Granger causality test:"
    print "Two-way causality:" + str(counter11_01)
    print "Correct causality:" + str(counter10_01)
    print "Wrong causality:" + str(counter01_01)
    print "No causality:" + str(counter00_01)
    print "-----------------"
    print "Encoding data, Our test:"
    print "Correct cause and effect:" + str(counter_true)
    print "Wrong cause and effect:" + str(counter_false)
    print "Undecided:" + str(counter_undecided)
    print "-----------------"
    """

    if is_causal:
        ourmodel = bh_procedure(p_array1, 0.05)
        #cute = bh_procedure(p_array_CUTE1, 0.05)
        cute = bh_procedure2(pros_cute,0.05)/1000.0
        improve_cute = bh_procedure(p_array_improve_CUTE1, 0.05)
        #print "Origin CUTE Accuracy:" + str(cute)
        #print "Improved CUTE Accuracy:" + str(improve_cute)
        #print "Our model Accuracy:" + str(ourmodel)
        new_model = bh_procedure2(pros1,0.05)/1000.0
    else:
        #ourmodel = (bh_procedure(p_array1, 0.05) + bh_procedure(p_array2, 0.05)) / 1000.0
        #cute = (bh_procedure(p_array_CUTE1, 0.05) + bh_procedure(p_array_CUTE2, 0.05)) / 1000.0
        cute = 1-bh_procedure2(pros_cute, 0.05)/1000.0
        improve_cute = (bh_procedure(p_array_improve_CUTE1, 0.05) + bh_procedure(p_array_improve_CUTE2, 0.05)) / 1000.0
        #print "Origin CUTE Accuracy:" + str(1 - cute)
        #print "Improved CUTE Accuracy:" + str(1 - improve_cute)
        #print "Our model Accuracy:" + str(1 - ourmodel)
        new_model = 1-(bh_procedure2(pros1, 0.05)) / 1000.0
    dict = {}
    dict['granger'] = [counter10,counter00]
    dict['grangerD'] = [counter10_01,counter00_01]
    dict['disc2'] = [cute]
    dict['disc'] = [new_model]
    print(pros_cute_counter)
    print('****************')
    return dict

def test_linear_data():
    noises = [0.0, 0.1, 0.2, 0.3]
    for noise in noises:
        dict = test_data(6, 600, 1, 1, 0, 0, noise)
        print dict['granger'][0]
        print dict['disc2'][0]
        print dict['disc'][0]


    for noise in noises:
        dict = test_data(6, 300, 1, 1, 0, 0, noise)
        print dict['granger'][0]
        print dict['disc2'][0]
        print dict['disc'][0]
    for noise in noises:
        dict = test_data(6, 400, 1, 1, 0, 0, noise)
        print dict['granger'][0]
        print dict['disc2'][0]
        print dict['disc'][0]
    for noise in noises:
        dict = test_data(6, 500, 1, 1, 0, 0, noise)
        print dict['granger'][0]
        print dict['disc2'][0]
        print dict['disc'][0]




def test_window_length_effect():
    start = 5
    end = 20
    result = []
    for i in range(start,end+1):
        x,y,z=test_data(i, 450, 1, 1, 0, 0, 0.1)
        result.append(z)
    print result


def test_non_linear():
    noises = [0.0, 0.1, 0.2, 0.3]
    for noise in noises:
        cute, improve_cute, ourmodel, counter10, counter00, counter10_01, counter00_01 = test_data(6, 600, 1, 0, 0, 0, noise)
        print "_____________200 "+str(noise)
        print counter10
        print improve_cute
        print ourmodel
        print "_____________"
    """
        for noise in noises:
        cute, improve_cute, ourmodel, counter10, counter00 = test_data(7, 300, 1, 0, 0, 0, noise)
        print "_____________300 " + str(noise)
        print counter10
        print improve_cute
        print ourmodel
        print "_____________"
    for noise in noises:
        cute, improve_cute, ourmodel, counter10, counter00 = test_data(8, 400, 1, 0, 0, 0, noise)
        print "_____________400 " + str(noise)
        print counter10
        print improve_cute
        print ourmodel
        print "_____________"
    for noise in noises:
        cute, improve_cute, ourmodel, counter10, counter00 = test_data(9, 500, 1, 0, 0, 0, noise)
        print "_____________500 " + str(noise)
        print counter10
        print improve_cute
        print ourmodel
        print "_____________"
    """



def test_no_causality_consistency():

    dict = test_data(6, 200, 0, 1, 0, 0, 0)
    print dict['granger'][1]
    print dict['grangerD'][1]
    print dict['disc2'][0]
    print dict['disc'][0]
    dict =test_data(7, 300, 0,1, 0, 0, 0)
    print dict['granger'][1]
    print dict['grangerD'][1]
    print dict['disc2'][0]
    print dict['disc'][0]
    dict =test_data(8, 400, 0, 1, 0, 0, 0)
    print dict['granger'][1]
    print dict['grangerD'][1]
    print dict['disc2'][0]
    print dict['disc'][0]
    dict =test_data(9, 500, 0, 1, 0, 0, 0)
    print dict['granger'][1]
    print dict['grangerD'][1]
    print dict['disc2'][0]
    print dict['disc'][0]
    dict =test_data(10, 600, 0, 1, 0, 0, 0)
    print dict['granger'][1]
    print dict['grangerD'][1]
    print dict['disc2'][0]
    print dict['disc'][0]

    dict =test_data(6, 200, 0, 1, 0, 1, 0)
    print dict['granger'][1]
    print dict['grangerD'][1]
    print dict['disc2'][0]
    print dict['disc'][0]
    dict =test_data(7, 300, 0, 1, 0, 1, 0)
    print dict['granger'][1]
    print dict['grangerD'][1]
    print dict['disc2'][0]
    print dict['disc'][0]
    dict =test_data(8, 400, 0, 1, 0, 1, 0)
    print dict['granger'][1]
    print dict['grangerD'][1]
    print dict['disc2'][0]
    print dict['disc'][0]
    dict =test_data(9, 500, 0, 1, 0, 1, 0)
    print dict['granger'][1]
    print dict['grangerD'][1]
    print dict['disc2'][0]
    print dict['disc'][0]
    dict =test_data(10, 600, 0, 1, 0, 1, 0)
    print dict['granger'][1]
    print dict['grangerD'][1]
    print dict['disc2'][0]
    print dict['disc'][0]


def test_causality_consistency():
    dict= test_data(6, 200, 1, 1, 0, 0, 0)
    print dict['granger'][0]
    print dict['grangerD'][0]
    print dict['disc2'][0]
    print dict['disc'][0]
    dict= test_data(7, 300, 1, 1, 0, 0, 0)
    print dict['granger'][0]
    print dict['grangerD'][0]
    print dict['disc2'][0]
    print dict['disc'][0]
    dict = test_data(8, 400, 1, 1, 0, 0, 0)
    print dict['granger'][0]
    print dict['grangerD'][0]
    print dict['disc2'][0]
    print dict['disc'][0]
    dict = test_data(9, 500, 1, 1, 0, 0, 0)
    print dict['granger'][0]
    print dict['grangerD'][0]
    print dict['disc2'][0]
    print dict['disc'][0]
    dict = test_data(10, 600, 1, 1, 0, 0, 0)
    print dict['granger'][0]
    print dict['grangerD'][0]
    print dict['disc2'][0]
    print dict['disc'][0]

    dict = test_data(6, 200, 1, 1, 0, 1, 0)
    print dict['granger'][0]
    print dict['grangerD'][0]
    print dict['disc2'][0]
    print dict['disc'][0]
    dict = test_data(7, 300, 1, 1, 0, 1, 0)
    print dict['granger'][0]
    print dict['grangerD'][0]
    print dict['disc2'][0]
    print dict['disc'][0]
    dict = test_data(8, 400, 1, 1, 0, 1, 0)
    print dict['granger'][0]
    print dict['grangerD'][0]
    print dict['disc2'][0]
    print dict['disc'][0]
    dict = test_data(9, 500, 1, 1, 0, 1, 0)
    print dict['granger'][0]
    print dict['grangerD'][0]
    print dict['disc2'][0]
    print dict['disc'][0]

    dict = test_data(10, 600, 1, 1, 0, 1, 0)
    print dict['granger'][0]
    print dict['grangerD'][0]
    print dict['disc2'][0]
    print dict['disc'][0]

def time_test_window(array_length, window_size):
    for i in range(0, 10):
        cause, effect = generate_continue_data(array_length, 3, 0)
        cause = zero_change(cause)
        effect = zero_change(effect)
        cause2effect = fast_calculate_difference(cause, effect, window_size)
        effect2cause = fast_calculate_difference(effect, cause, window_size)


def time_test_weighted_window(array_length, window_size):
    for i in range(0, 10):
        cause, effect = generate_continue_data(array_length, 3, 0)
        cause = zero_change(cause)
        effect = zero_change(effect)
        cause2effect = calculate_difference_with_weight_window(cause, effect, 0.7, window_size)
        effect2cause = calculate_difference_with_weight_window(effect, cause, 0.7, window_size)


def time_test_weighted(array_length, window_size):
    for i in range(0, 10):
        cause, effect = generate_continue_data(array_length, 3, 0)
        cause = zero_change(cause)
        effect = zero_change(effect)
        cause2effect = calculate_difference_with_weight_window(cause, effect, 0.5,window_size)
        effect2cause = calculate_difference_with_weight_window(effect, cause, 0.5,window_size)


def time_window():
    times = []
    xs = []
    for i in range(100, 5100, 100):
        xs.append(i / 100)
        start = time.clock()
        time_test_window(i, 12)
        end = time.clock()
        times.append((end - start) / 10)
    print xs
    print times
    plt.plot(xs, times)
    plt.xlabel("Length($\\times10^2$)")
    plt.ylabel("Time Per Series(/s)")
    plt.show()


def time_weighted():
    times = []
    xs = []
    for i in range(100, 2000, 100):
        xs.append(i / 100)
        start = time.clock()
        time_test_weighted(i, 6)
        end = time.clock()
        times.append((end - start) / 10)
    plt.plot(xs, times)
    plt.xlabel("Length($\\times10^2$)")
    plt.ylabel("Time Per Series(/s)")
    plt.show()


def time_weighted_window():
    times = []
    xs = []
    for i in range(100, 5100, 100):
        xs.append(i / 100)
        start = time.clock()
        time_test_weighted(i, 12)
        end = time.clock()
        times.append((end - start) / 10)
    print xs
    print times
    plt.plot(xs, times)
    plt.xlabel("Length($\\times10^2$)")
    plt.ylabel("Time Per Series(/s)")
    plt.show()


def test_window(length,shift):
    causes = []
    effects = []
    results = []
    for i in range(0,1000):
        cause, effect = generate_continue_data(length,shift,0.0)
        cause = zero_change(cause)
        effect = zero_change(effect)
        #cause = zero_change(cause)
        #effect = zero_change(effect)
        #cause2 = get_type_array_with_quantile(cause)
        #effect2 = get_type_array_with_quantile(effect)
        causes.append(cause)
        effects.append(effect)

    for j in range(3,26):
        p_array = []
        for i in range(0,len(causes)):
            cause = causes[i]
            effect = effects[i]
            delta_ce = calculate_difference(cause, effect, j)
            delta_ec = calculate_difference(effect, cause, j)
            p = math.pow(2, -(delta_ce - delta_ec))
            p_array.append(p)
        ourmodel = bh_procedure(p_array, 0.05)
        results.append(ourmodel/1000.0)
    print results


def test_window_granger(length,shift):
    causes = []
    effects = []
    results11 = []
    results10 = []
    results01 = []
    results00 = []
    for i in range(0,1000):
        cause, effect = generate_continue_data(length,shift,0.0)
        #effect, effect2 = generate_continue_data(length, shift, 0.1)
        cause = zero_change(cause)
        effect = zero_change(effect)
        #cause2 = get_type_array_with_quantile(cause)
        #effect2 = get_type_array_with_quantile(effect)
        causes.append(cause)
        effects.append(effect)

    for j in range(3,26):
        counter11 = 0
        counter10=0
        counter01 = 0
        counter00 = 0
        for i in range(0,len(causes)):
            cause = causes[i]
            effect = effects[i]
            flag1 = False
            ce_p = granger(cause, effect, j)
            if ce_p < 0.05:
                flag1 = True
            flag2 = False
            ce2_p = granger(effect, cause, j)
            if ce2_p < 0.05:
                flag2 = True
            if flag1 and flag2:
                counter11 += 1
            elif flag1 and not flag2:
                counter10 += 1
            elif not flag1 and flag2:
                counter01 += 1
            elif not flag1 and not flag2:
                counter00 += 1
        results11.append(counter11/1000.0)
        results01.append(counter01/1000.0)
        results10.append(counter10/1000.0)
        results00.append(counter00/1000.0)
    return results11,results10,results01,results00

def test_icute_window(length,shift):
    causes = []
    effects = []
    results = []
    for i in range(0, 1000):
        cause, effect = generate_continue_data(length, shift, 0.1)
        cause = zero_change(cause)
        effect = zero_change(effect)
        # cause2 = get_type_array_with_quantile(cause)
        # effect2 = get_type_array_with_quantile(effect)
        causes.append(cause)
        effects.append(effect)

    for j in range(3, 26):
        p_array = []
        for i in range(0, len(causes)):
            cause = change_to_zero_one(causes[i])
            effect = change_to_zero_one(effects[i])
            cause2effect = bernoulli2(effect, j) - cbernoulli2(effect, cause, j)
            effect2cause = bernoulli2(cause, j) - cbernoulli2(cause, effect, j)
            p = math.pow(2, -(cause2effect - effect2cause))
            p_array.append(p)
        icute = bh_procedure(p_array, 0.05)
        results.append(icute / 1000.0)
    print results


from random import choice

def test_change_window():
    lengths = [150,250,350,450]
    lags = [1,2,3,4,5,6,7]
    segments = [2,3,4,5]
    causes = []
    effects = []
    for k in range(0,1000):
        cause = []
        effect = []
        num = choice(segments)
        for i in range(0,num):
            c, e = generate_continue_data(choice(lengths), choice(lags), 0.1)
            c = zero_change(c)
            e = zero_change(e)
            cause.extend(c)
            effect.extend(e)
        causes.append(cause)
        effects.append(effect)
    p_array = []
    for i in range(0, len(causes)):
        cause = causes[i]
        effect = effects[i]
        delta_ce = calculate_difference(cause, effect, 10)
        delta_ec = calculate_difference(effect, cause, 10)
        p = math.pow(2, -(delta_ce - delta_ec))
        p_array.append(p)
    ourmodel = bh_procedure(p_array, 0.05)
    print ourmodel


def test_change_window_icute():
    lengths = [150, 250, 350, 450]
    lags = [1, 2, 3, 4, 5, 6, 7]
    segments = [2, 3, 4, 5]
    causes = []
    effects = []
    for k in range(0, 1000):
        cause = []
        effect = []
        num = choice(segments)
        for i in range(0, num):
            c, e = generate_continue_data(choice(lengths), choice(lags), 0.1)
            c = zero_change(c)
            e = zero_change(e)
            cause.extend(c)
            effect.extend(e)
        causes.append(cause)
        effects.append(effect)
    p_array = []
    for i in range(0, len(causes)):
        cause = change_to_zero_one(causes[i])
        effect = change_to_zero_one(effects[i])
        cause2effect = bernoulli2(effect, 10) - cbernoulli2(effect, cause, 10)
        effect2cause = bernoulli2(cause, 10) - cbernoulli2(cause, effect, 10)
        p = math.pow(2, -(cause2effect - effect2cause))
        p_array.append(p)
    icute = bh_procedure(p_array, 0.05)
    print icute


def test_change_window_granger():
    lengths = [150, 250, 350, 450]
    lags = [1, 2, 3, 4, 5, 6, 7]
    segments = [2, 3, 4, 5]
    causes = []
    effects = []
    for k in range(0, 1000):
        cause = []
        effect = []
        num = choice(segments)
        for i in range(0, num):
            c, e = generate_continue_data(choice(lengths), choice(lags), 0.1)
            c = zero_change(c)
            e = zero_change(e)
            cause.extend(c)
            effect.extend(e)
        causes.append(cause)
        effects.append(effect)
    p_array = []
    counter11 =0
    counter10 = 0
    counter01 = 0
    counter00 = 0
    for i in range(0, len(causes)):
        cause = causes[i]
        effect = effects[i]
        flag1 = False
        ce_p = granger(cause, effect, -1)
        if ce_p < 0.05:
            flag1 = True
        flag2 = False
        ce2_p = granger(effect, cause, -1)
        if ce2_p < 0.05:
            flag2 = True
        if flag1 and flag2:
            counter11 += 1
        elif flag1 and not flag2:
            counter10 += 1
        elif not flag1 and flag2:
            counter01 += 1
        elif not flag1 and not flag2:
            counter00 += 1
    print counter11
    print counter10
    print counter01
    print counter00


def test_coding(length,window_length):
    causes = []
    effects = []
    results = []
    for i in range(0,1000):
        cause, effect = generate_continue_data(length,random.randint(1,3),0.0)
        effect, effect3 = generate_continue_data(length, random.randint(1, 3), 0.0)
        #cause = np.random.standard_normal(length)
        #effect = np.random.standard_normal(length)
        cause = zero_change(cause)
        effect = zero_change(effect)
        cause = zero_change(cause)
        effect = zero_change(effect)
        causes.append(cause)
        effects.append(effect)
    qs = [0.05,0.1,0.15,0.20,0.25,0.30,0.35,0.40,0.45]
    for q in qs:
        p_array = []
        p_array2 = []
        for i in range(0,len(causes)):
            cause = causes[i]
            effect = effects[i]
            delta_ce = calculate_difference_with_quantile(cause, effect, window_length,q)
            delta_ec = calculate_difference_with_quantile(effect, cause, window_length,q)
            p = math.pow(2, -(delta_ce - delta_ec))
            p_array.append(p)
            p2 = math.pow(2, -(delta_ec - delta_ce))
            p_array2.append(p2)
        #ourmodel = bh_procedure(p_array, 0.05)
        ourmodel = (bh_procedure(p_array, 0.05) + bh_procedure(p_array2, 0.05)) / 1000.0
        results.append(1-ourmodel)
    print results


def test_coding2(length,window_length):
    causes = []
    effects = []
    results = []
    for i in range(0,1000):
        cause, effect = generate_continue_data(length,random.randint(1,3),0.1)
        effect, effect3 = generate_continue_data(length, random.randint(1, 3), 0.1)
        cause = zero_change(cause)
        effect = zero_change(effect)
        cause = zero_change(cause)
        effect = zero_change(effect)
        causes.append(cause)
        effects.append(effect)
    qs = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]
    for q in qs:
        p_array = []
        for i in range(0,len(causes)):
            cause = causes[i]
            effect = effects[i]
            delta_ce = calculate_difference_with_quantile2(cause, effect, window_length,q)
            delta_ec = calculate_difference_with_quantile2(effect, cause, window_length,q)
            p = math.pow(2, -(delta_ce - delta_ec))
            p_array.append(p)
        ourmodel = bh_procedure(p_array, 0.05)
        results.append(1-ourmodel/1000.0)
    print results

def test_motivation(length):
    p_array = []
    counter =0
    for i in range(0,1000):
        x1 = np.random.normal(0, 1, length)
        x2 = np.random.normal(0, 1, length)
        y = []
        for j in range(0,length):
            y.append(x1[j]+x2[j])
        forward_shift_continue_data(y,5)
        delta_ce = calculate_difference(x1, y, 10)
        delta_ec = calculate_difference(y, x1, 10)
        p = math.pow(2, -(delta_ce - delta_ec))
        p_array.append(p)
        if p<=0.5:
            counter+=1
    outmodel = bh_procedure(p_array,0.05)
    print outmodel
    print counter


def smooth(values,window):
    ans =[]
    left = window/2
    right = window /2
    for i in range(0,len(values)):
        if i<left or i >= len(values)-right:
            ans.append(values[i])
        else:
            value = 0
            for w in range(1,left+1):
                value +=values[i-w]
            for w in range(1,right+1):
                value+=values[i+w]
            value+=values[i]
            value = value/(left+right+1)
            ans.append(value)
    return ans


def detect_segment(values,min_length):
    delta = -math.log(0.05,2)
    pos_cau_start = []
    pos_cau_end = []
    neg_cau_start = []
    neg_cau_end = []
    i = 1
    difference = 0
    start = 0
    end = 1
    if values[start]<values[end]:
        up = True
    else:
        up = False
    while i<len(values):
        if up:
            if values[i]>values[i-1]:
                end = i
                difference = values[end]-values[start]
            else:
                if (abs(difference) > delta) and end-start>min_length:
                    pos_cau_start.append(start)
                    pos_cau_end.append(end)
                start = i-1
                end = i

                up = False
                difference = values[end]-values[start]
        else:
            if values[i]<values[i-1]:
                end = i
                difference = values[end]-values[start]
            else:
                if (abs(difference) > delta) and end-start>min_length:
                    neg_cau_start.append(start)
                    neg_cau_end.append(end)
                start = i-1
                end = i

                up = True
                difference = values[end] - values[start]
        i+=1
    if (abs(difference) > delta) and end - start > min_length:
        if difference<0:
            neg_cau_start.append(start)
            neg_cau_end.append(end)
        else:
            pos_cau_start.append(start)
            pos_cau_end.append(end)
    print pos_cau_start
    print pos_cau_end
    print neg_cau_start
    print neg_cau_end
    return pos_cau_start,pos_cau_end,neg_cau_start,neg_cau_end


def detect_segment2(values,min_length):
    delta = -math.log(0.05,2)
    pos_cau_start = []
    pos_cau_end = []
    neg_cau_start = []
    neg_cau_end = []
    i = 1
    difference = 0
    start = 0
    end = 1
    state = up_down(values,0.9,0,20)
    curLen = 0
    for i in range(1,len(values)):
        tmp_state = up_down(values,0.9,i,20)
        if tmp_state==state:
            curLen+=1
        else:
            if curLen>=min_length:
                if state==1 and abs(values[i-curLen]-values[i])>delta:
                    pos_cau_start.append(i-curLen)
                    pos_cau_end.append(i)
                elif state == -1 and abs(values[i-curLen]-values[i])>delta:
                    neg_cau_start.append(i-curLen)
                    neg_cau_end.append(i)
            state = tmp_state
            curLen = 0

    if curLen >= min_length:
        if state == 1 and abs(values[i - curLen] - values[i]) > delta:
            pos_cau_start.append(i - curLen)
            pos_cau_end.append(i)
        elif state == -1 and abs(values[i - curLen] - values[i]) > delta:
            neg_cau_start.append(i - curLen)
            neg_cau_end.append(i)
        curLen = 0
    #print pos_cau_start
    #print pos_cau_end
    #print neg_cau_start
    #print neg_cau_end
    return pos_cau_start,pos_cau_end,neg_cau_start,neg_cau_end


# Definition for an interval.
class Interval:
     def __init__(self, s=0, e=0):
         self.start = s
         self.end = e

import operator
def intervalIntersection(A,B):
    m = len(A)
    n = len(B)
    cmpfun = operator.attrgetter('start','end')
    A.sort(key=cmpfun)
    B.sort(key=cmpfun)
    res = []
    i = 0
    j = 0
    while i < m and j < n:
        left = max(A[i].start, B[j].start)
        if A[i].end < B[j].end:
            right = A[i].end
            i += 1
        else:
            right = B[j].end
            j += 1
        if left <= right:
            res.append(Interval(left, right))
    return res


def get_trend(a):
    result = []
    for i in range(0,len(a)):
        if i==len(a)-1:
            result.append(1)
        else:
            if a[i]>a[i+1]:
                result.append(0)
            else:
                result.append(1)
    return result


def up_down(a, th, index, window):
    x = get_trend(a)
    counter = 0
    length = 0
    if index+window>=len(x):
        length = len(x)-index
        for i in range(0,length):
            if x[index+i]==1:
                counter+=1
    else:
        length = window
        for i in range(0,length):
            if x[index+i]==1:
                counter+=1
    value = float(counter)/length
    if value>th:
        return 1
    elif value<1-th:
        return -1
    return 0








from real_data_test import ozone_mix
def test_segment_causality():
    c = [0,1,0,1,0,1]
    causes = []
    effects2 = []
    tmp_causes = []
    tmp_effects2 = []
    effects = []
    causes2 = []
    tmp_effects = []
    tmp_causes2 = []
    values = []
    for i in c:
        if i==0:
            effect, cause = generate_continue_data(1000, random.randint(1, 3), 0.1)
            effect, xx = generate_continue_data(1000, random.randint(1, 3), 0.1)
            tmp_causes.extend(cause)
            tmp_effects.extend(effect)
            cause = zero_change(cause)
            effect = zero_change(effect)
            #cause = zero_change(cause)
            #effect = zero_change(effect)
            causes.extend(cause)
            effects.extend(effect)
        else:
            cause, effect = generate_continue_data(1000, random.randint(1, 3), 0.0)
            tmp_causes.extend(cause)
            tmp_effects.extend(effect)
            cause = zero_change(cause)
            effect = zero_change(effect)
            causes.extend(cause)
            effects.extend(effect)
    #causes, effects = ozone_mix()
    #tmp_causes = causes
    #tmp_effects = effects
    #causes = zero_change(causes)
    #effects = zero_change(effects)
    causes2= causes[::-1]
    effects2 = effects[::-1]
    for l in range(0,7):
        values.append(0)
    #print tmp_causes
    #print tmp_effects
    #f = open('tmp_causes2', 'w')
    #for x in tmp_causes:
    #    print >> f,x
        #print x
    #f.close()
    #f = open('tmp_effects2', 'w')
    #for x in tmp_effects:
    #    print >> f, x
        #print x
    #f.close()
    delta_ces = calculate_difference_step(causes, effects, 6)
    delta_ecs = calculate_difference_step(effects, causes, 6)
    for i in range(0,len(delta_ces)):
        values.append(delta_ces[i]-delta_ecs[i])
    values = smooth(values,100)
    #f = open('values2', 'w')
    #for x in values:
    #    print >> f, x
        #print x
    #f.close()
    pos_cau_start, pos_cau_end, neg_cau_start, neg_cau_end = detect_segment2(values,100)
    As = []
    for i in range(0, len(pos_cau_start)):
        As.append(Interval(pos_cau_start[i], pos_cau_end[i]))
    for i in range(0,len(pos_cau_start)):
        tmp_x = []
        tmp_y = []
        for j in range(pos_cau_start[i],pos_cau_end[i]):
            tmp_x.append(j)
            tmp_y.append(0)
        #plt.plot(tmp_x,tmp_y,c='r',linewidth=5.0)
    for i in range(0,len(neg_cau_start)):
        tmp_x = []
        tmp_y = []
        for i in range(neg_cau_start[i],neg_cau_end[i]):
            tmp_x.append(i)
            tmp_y.append(0)
        #plt.plot(tmp_x,tmp_y,c='g',linewidth=5.0)
    font1 = {'family': 'Times New Roman',
             'weight': 'normal',
             'size': 23,
             }
    #plt.plot(tmp_causes,label="cause")
    #plt.plot(tmp_effects,label="effect")
    #plt.xlabel("x",font1)
    #plt.ylabel("y",font1)
    #foo_fig = plt.gcf()  # 'get current figure'
    #foo_fig.savefig('dy.eps', format='eps')
    #plt.show()
    for i in range(0,len(pos_cau_start)):
        tmp_x = []
        tmp_y = []
        for i in range(pos_cau_start[i],pos_cau_end[i]):
            tmp_x.append(i)
            tmp_y.append(0)
        #plt.plot(tmp_x,tmp_y,c='r',linewidth=5.0)
    for i in range(0,len(neg_cau_start)):
        tmp_x = []
        tmp_y = []
        for i in range(neg_cau_start[i],neg_cau_end[i]):
            tmp_x.append(i)
            tmp_y.append(0)
        #plt.plot(tmp_x,tmp_y,c='g',linewidth=5.0)
    #plt.xlabel("x",font1)
    #plt.ylabel('$\Delta$',font1)
    #plt.plot(values)
    #foo_fig = plt.gcf()  # 'get current figure'
    #foo_fig.savefig('dy_v.eps', format='eps')
    #plt.show()

    values = []
    delta_ces = calculate_difference_step(effects2, causes2, 6)
    delta_ecs = calculate_difference_step(causes2, effects2, 6)
    for i in range(0, len(delta_ces)):
        values.append(delta_ces[i] - delta_ecs[i])
    values = values[::-1]
    values = smooth(values, 50)
    #f = open('values2', 'w')
    #for x in values:
        #print >> f, x
        #print x
    #f.close()
    pos_cau_start, pos_cau_end, neg_cau_start, neg_cau_end = detect_segment2(values, 100)
    Bs = []
    for i in range(0,len(neg_cau_start)):
        Bs.append(Interval(neg_cau_start[i],neg_cau_end[i]))


    for i in range(0, len(pos_cau_start)):
        tmp_x = []
        tmp_y = []
        for j in range(pos_cau_start[i], pos_cau_end[i]):
            tmp_x.append(j)
            tmp_y.append(0)
        #plt.plot(tmp_x, tmp_y, c='r', linewidth=5.0)
    for i in range(0, len(neg_cau_start)):
        tmp_x = []
        tmp_y = []
        for i in range(neg_cau_start[i], neg_cau_end[i]):
            tmp_x.append(i)
            tmp_y.append(0)
        #plt.plot(tmp_x, tmp_y, c='g', linewidth=5.0)
    font1 = {'family': 'Times New Roman',
             'weight': 'normal',
             'size': 23,
             }
    #plt.plot(tmp_causes, label="cause")
    #plt.plot(tmp_effects, label="effect")
    #plt.xlabel("x", font1)
    #plt.ylabel("y", font1)
    #foo_fig = plt.gcf()  # 'get current figure'
    #foo_fig.savefig('dy.eps', format='eps')
    #plt.show()
    for i in range(0, len(pos_cau_start)):
        tmp_x = []
        tmp_y = []
        for i in range(pos_cau_start[i], pos_cau_end[i]):
            tmp_x.append(i)
            tmp_y.append(0)
        #plt.plot(tmp_x, tmp_y, c='r', linewidth=5.0)
    for i in range(0, len(neg_cau_start)):
        tmp_x = []
        tmp_y = []
        for i in range(neg_cau_start[i], neg_cau_end[i]):
            tmp_x.append(i)
            tmp_y.append(0)
        #plt.plot(tmp_x, tmp_y, c='g', linewidth=5.0)
    #plt.xlabel("x", font1)
    #plt.ylabel('$\Delta$', font1)
    #plt.plot(values)
    #foo_fig = plt.gcf()  # 'get current figure'
    #foo_fig.savefig('dy_v.eps', format='eps')
    #plt.show()
    res = intervalIntersection(As,Bs)
    #for i in res:
        #print str(i.start) + " " + str(i.end)
    s1 = Interval(1000,2000)
    s2 = Interval(3000, 4000)
    s3 = Interval(5000, 6000)

    s4 = Interval(0, 1000)
    s5 = Interval(2000, 3000)
    s6 = Interval(4000, 5000)
    cau_seg = [s1,s2,s3]
    no_cau_seg = [s4, s5, s6]
    total_recall_points = 0
    res2 = intervalIntersection(cau_seg,res)
    for i in res2:
        total_recall_points= total_recall_points+i.end-i.start
    recall = total_recall_points/3000.0
    total_wrong_points = 0
    res3 = intervalIntersection(no_cau_seg,res)
    for i in res3:
        print str(i.start) + " " + str(i.end)
    for i in res3:
        total_wrong_points= total_wrong_points+i.end-i.start
    pre =  1-total_wrong_points/3000.0
    return recall,pre


def test_segment_causality2(noise):
    choices = [0,-1,1]
    pos_segment = []
    neg_segment = []
    no_segment = []
    causes = []
    effects2 = []
    tmp_causes = []
    tmp_effects2 = []
    effects = []
    causes2 = []
    tmp_effects = []
    tmp_causes2 = []
    values = []
    cau_seg_counter = 0
    for j in range(0,6):
        i = random.sample(choices,1)[0]
        if i==1:
            cau_seg_counter+=1
            pos_segment.append([j*1000,(j+1)*1000])
            cause, effect = generate_continue_data(1000, random.randint(1, 3), noise)
            tmp_causes.extend(cause)
            tmp_effects.extend(effect)
            cause = zero_change(cause)
            effect = zero_change(effect)
            #cause = zero_change(cause)
            #effect = zero_change(effect)
            causes.extend(cause)
            effects.extend(effect)
        elif i==-1:
            cau_seg_counter+=1
            neg_segment.append([j * 1000, (j + 1) * 1000])
            effect, cause = generate_continue_data(1000, random.randint(1, 3), noise)
            tmp_causes.extend(cause)
            tmp_effects.extend(effect)
            cause = zero_change(cause)
            effect = zero_change(effect)
            causes.extend(cause)
            effects.extend(effect)
        else:
            no_segment.append([j * 1000, (j + 1) * 1000])
            cause, xx = generate_continue_data(1000, random.randint(1, 3), 0.1)
            effect, xx = generate_continue_data(1000, random.randint(1, 3), 0.1)
            tmp_causes.extend(cause)
            tmp_effects.extend(effect)
            cause = zero_change(cause)
            effect = zero_change(effect)
            causes.extend(cause)
            effects.extend(effect)
    #causes, effects = ozone_mix()
    #tmp_causes = causes
    #tmp_effects = effects
    #causes = zero_change(causes)
    #effects = zero_change(effects)
    causes2= causes[::-1]
    effects2 = effects[::-1]
    for l in range(0,7):
        values.append(0)
    #print tmp_causes
    #print tmp_effects
    #f = open('tmp_causes2', 'w')
    #for x in tmp_causes:
    #    print >> f,x
        #print x
    #f.close()
    #f = open('tmp_effects2', 'w')
    #for x in tmp_effects:
    #    print >> f, x
        #print x
    #f.close()
    delta_ces = calculate_difference_step(causes, effects, 6)
    delta_ecs = calculate_difference_step(effects, causes, 6)
    for i in range(0,len(delta_ces)):
        values.append(delta_ces[i]-delta_ecs[i])
    values = smooth(values,100)
    #f = open('values2', 'w')
    #for x in values:
    #    print >> f, x
        #print x
    #f.close()
    pos_cau_start, pos_cau_end, neg_cau_start, neg_cau_end = detect_segment2(values,100)
    As = []
    As2 = []
    for i in range(0, len(pos_cau_start)):
        As.append(Interval(pos_cau_start[i], pos_cau_end[i]))
    for i in range(0,len(neg_cau_start)):
        As2.append(Interval(neg_cau_start[i],neg_cau_end[i]))
    for i in range(0,len(pos_cau_start)):
        tmp_x = []
        tmp_y = []
        for j in range(pos_cau_start[i],pos_cau_end[i]):
            tmp_x.append(j)
            tmp_y.append(0)
        #plt.plot(tmp_x,tmp_y,c='r',linewidth=5.0)
    for i in range(0,len(neg_cau_start)):
        tmp_x = []
        tmp_y = []
        for i in range(neg_cau_start[i],neg_cau_end[i]):
            tmp_x.append(i)
            tmp_y.append(0)
        #plt.plot(tmp_x,tmp_y,c='g',linewidth=5.0)
    font1 = {'family': 'Times New Roman',
             'weight': 'normal',
             'size': 23,
             }
    #plt.plot(tmp_causes,label="cause")
    #plt.plot(tmp_effects,label="effect")
    #plt.xlabel("x",font1)
    #plt.ylabel("y",font1)
    #foo_fig = plt.gcf()  # 'get current figure'
    #foo_fig.savefig('dy.eps', format='eps')
    #plt.show()
    for i in range(0,len(pos_cau_start)):
        tmp_x = []
        tmp_y = []
        for i in range(pos_cau_start[i],pos_cau_end[i]):
            tmp_x.append(i)
            tmp_y.append(0)
        #plt.plot(tmp_x,tmp_y,c='r',linewidth=5.0)
    for i in range(0,len(neg_cau_start)):
        tmp_x = []
        tmp_y = []
        for i in range(neg_cau_start[i],neg_cau_end[i]):
            tmp_x.append(i)
            tmp_y.append(0)
        #plt.plot(tmp_x,tmp_y,c='g',linewidth=5.0)
    #plt.xlabel("x",font1)
    #plt.ylabel('$\Delta$',font1)
    #plt.plot(values)
    #foo_fig = plt.gcf()  # 'get current figure'
    #foo_fig.savefig('dy_v.eps', format='eps')
    #plt.show()

    values = []
    delta_ces = calculate_difference_step(effects2, causes2, 6)
    delta_ecs = calculate_difference_step(causes2, effects2, 6)
    for i in range(0, len(delta_ces)):
        values.append(delta_ces[i] - delta_ecs[i])
    #values = values[::-1]
    values = smooth(values, 100)
    #f = open('values2', 'w')
    #for x in values:
        #print >> f, x
        #print x
    #f.close()
    pos_cau_start, pos_cau_end, neg_cau_start, neg_cau_end = detect_segment2(values, 100)
    Bs = []
    Bs2 = []
    for i in range(0,len(pos_cau_start)):
        Bs.append(Interval(6000-pos_cau_end[i],6000-pos_cau_start[i]))
    for i in range(0,len(neg_cau_start)):
        Bs2.append(Interval(6000-neg_cau_end[i],6000-neg_cau_start[i]))


    for i in range(0, len(pos_cau_start)):
        tmp_x = []
        tmp_y = []
        for j in range(pos_cau_start[i], pos_cau_end[i]):
            tmp_x.append(j)
            tmp_y.append(0)
        #plt.plot(tmp_x, tmp_y, c='r', linewidth=5.0)
    for i in range(0, len(neg_cau_start)):
        tmp_x = []
        tmp_y = []
        for i in range(neg_cau_start[i], neg_cau_end[i]):
            tmp_x.append(i)
            tmp_y.append(0)
        #plt.plot(tmp_x, tmp_y, c='g', linewidth=5.0)
    font1 = {'family': 'Times New Roman',
             'weight': 'normal',
             'size': 23,
             }
    #plt.plot(tmp_causes, label="cause")
    #plt.plot(tmp_effects, label="effect")
    #plt.xlabel("x", font1)
    #plt.ylabel("y", font1)
    #foo_fig = plt.gcf()  # 'get current figure'
    #foo_fig.savefig('dy.eps', format='eps')
    #plt.show()
    for i in range(0, len(pos_cau_start)):
        tmp_x = []
        tmp_y = []
        for i in range(pos_cau_start[i], pos_cau_end[i]):
            tmp_x.append(i)
            tmp_y.append(0)
        #plt.plot(tmp_x, tmp_y, c='r', linewidth=5.0)
    for i in range(0, len(neg_cau_start)):
        tmp_x = []
        tmp_y = []
        for i in range(neg_cau_start[i], neg_cau_end[i]):
            tmp_x.append(i)
            tmp_y.append(0)
        #plt.plot(tmp_x, tmp_y, c='g', linewidth=5.0)
    #plt.xlabel("x", font1)
    #plt.ylabel('$\Delta$', font1)
    #plt.plot(values)
    #foo_fig = plt.gcf()  # 'get current figure'
    #foo_fig.savefig('dy_v.eps', format='eps')
    #plt.show()
    res = intervalIntersection(As,Bs)
    #for i in res:
        #print str(i.start) + " " + str(i.end)
    pos_cau_seg_detect = intervalIntersection(As, Bs)
    neg_cau_seg_detect = intervalIntersection(As2,Bs2)
    real_pos_segment = []
    real_neg_segment = []
    for element in pos_segment:
        real_pos_segment.append(Interval(element[0],element[1]))
    for element in neg_segment:
        real_neg_segment.append(Interval(element[0], element[1]))

    total_recall_points = 0
    res2 = intervalIntersection(real_pos_segment,pos_cau_seg_detect)
    res2.extend(intervalIntersection(neg_cau_seg_detect,real_neg_segment))
    for i in res2:
        total_recall_points= total_recall_points+i.end-i.start
    recall = total_recall_points/float(cau_seg_counter*1000)
    total_points_num = 0
    for element in pos_cau_seg_detect:
        total_points_num = total_points_num + element.end -element.start
    for element in neg_cau_seg_detect:
        total_points_num = total_points_num + element.end -element.start
    pre = float(total_recall_points)/total_points_num
    #print(recall)
    #print(pre)
    return recall,pre





if __name__ == '__main__':
    #test_causality_consistency()
    #test_no_causality_consistency()

    #test_linear_data()
    #test_non_linear()
    #test_coding(200,6)
    #test_coding(300, 7)
    #test_coding(400, 8)
    #test_coding(500, 9)
    #test_coding(600, 10)
    #time_window()
    #time_weighted()
    #time_weighted_window()
    #results11,result10,result01,results00 = test_window_granger(240,5)

    recalls = []
    pres = []
    f1s = []
    for noise in [0,0.1,0.2,0.3]:
        print(noise)
        print("---------------------------------------------")
        for i in range(0,100):
            recall , pre = test_segment_causality2(noise)
            recalls.append(recall)
            pres.append(pre)
            f1s.append(2*pre*recall/(pre+recall))
        print max(recalls)
        print min(recalls)

        print max(pres)
        print min(pres)

        print max(f1s)
        print min(f1s)


        print np.std(pres)
        print np.std(recalls)
        print np.std(f1s)

        print np.average(pres)
        print np.average(recalls)
        print np.average(f1s)


    #test_window_length_effect()

    #test_motivation(2850)
    for i in range(4,11,2):
        print "***********"+str(i)+"*****************"
        test_window(200,i)
        test_window(300, i)
        test_window(400,i)
        test_window(500, i)
        test_window(600, i)
        test_window(700, i)
        test_window(800, i)
        test_window(900, i)
        #test_icute_window(150,i)
        #test_icute_window(250, i)
        #test_icute_window(350, i)
        #test_icute_window(450, i)
        #test_icute_window(550, i)
        #test_icute_window(650, i)
        #test_icute_window(750, i)
        #test_icute_window(850, i)
        """
        results11, result10, result01, results00 = test_window_granger(150, i)
        print results11
        print result10
        print result01
        print results00
        print "-------------------------------------------"
        results11, result10, result01, results00 = test_window_granger(250, i)
        print results11
        print result10
        print result01
        print results00
        print "-------------------------------------------"
        results11, result10, result01, results00 = test_window_granger(350, i)
        print results11
        print result10
        print result01
        print results00
        print "-------------------------------------------"
        results11, result10, result01, results00 = test_window_granger(450, i)
        print results11
        print result10
        print result01
        print results00
        print "-------------------------------------------"
        results11, result10, result01, results00 = test_window_granger(550, i)
        print results11
        print result10
        print result01
        print results00
        print "-------------------------------------------"
        results11, result10, result01, results00 = test_window_granger(650, i)
        print results11
        print result10
        print result01
        print results00
        print "-------------------------------------------"
        results11, result10, result01, results00 = test_window_granger(750, i)
        print results11
        print result10
        print result01
        print results00
        print "-------------------------------------------"
        results11, result10, result01, results00 = test_window_granger(850, i)
        print results11
        print result10
        print result01
        print results00
        print "-------------------------------------------"
"""
    #test_change_window()
    #test_change_window_icute()
    #test_change_window_granger()
    #test_coding(150,6)
    #test_coding(250, 7)
    #test_coding(350, 8)
    #test_coding(450, 9)

